repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: check-yaml
    - id: check-toml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: mixed-line-ending
    - id: pretty-format-json
      args: [ --autofix ]
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        stages: [ commit-msg ]
        language: system
        entry: poetry run cz check --commit-msg-file
        types: [ python ]
  - repo: local
    hooks:
        - id: pytest-check
          name: pytest-check
          entry: pytest
          language: system
          pass_filenames: false
          always_run: true
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [ --fail-under=80, --verbose ]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        args: [ --ignore=D107,D204 ]
  - repo: local
    hooks:
      - id: pdoc
        name: pdoc
        language: system
        pass_filenames: false
        entry: pdoc --html -f utils -o docs
  - repo: local
    hooks:
      - id: wily
        name: wily
        entry: wily diff
        verbose: true
        language: python
        additional_dependencies: [ wily ]
